# TODO The private key generated by this resource will be stored unencrypted in your Terraform state file.
# Generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run instead.

resource "oci_identity_compartment" "freecloud" {
  compartment_id = var.parent_compartment_id
  name           = var.compartment_name
  description    = var.compartment_description
  freeform_tags  = var.common_tags
}

resource "tls_private_key" "ssh" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}

module "base" {
  source         = "./modules/base"
  compartment_id = oci_identity_compartment.freecloud.id
  tags           = var.common_tags
}

# module "k3s_cluster" {
#   source         = "./modules/k3s-cluster"
#   server_count   = 1
#   agent_count    = 3
#   ssh_public_key = tls_private_key.ssh.public_key_openssh
#   subnet_id      = module.network.subnet_id
# }
