apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: app-engine
spec:
  destination:
    name: in-cluster
    namespace: app-engine
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 3.7.3
    helm:
      valuesObject:
        defaultPodOptions:
          restartPolicy: Always
          labels:
            istio.io/dataplane-mode: ambient
          hostNetwork: true
        controllers:
          worker:
            strategy: RollingUpdate
            containers:
              app:
                image:
                  # TODO bootstrap and build itself
                  # repository: zot.zot.svc.cluster.local/khuedoan/app-engine
                  repository: docker.io/khuedoan/app-engine
                  tag: 4118f90
                  pullPolicy: Always
                env:
                  TEMPORAL_URL: http://temporal-frontend.temporal:7233
                  REGISTRY: zot.zot.svc.cluster.local
              docker:
                image:
                  repository: docker.io/library/docker
                  tag: 27-dind
                command:
                  - dockerd
                  - --host=unix:///var/run/docker.sock
                  - --insecure-registry=zot.zot.svc.cluster.local
                securityContext:
                  privileged: true
        persistence:
          socket:
            type: emptyDir
            globalMounts:
              - path: /var/run
                subPath: docker.sock
