apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: temporal
spec:
  destination:
    name: in-cluster
    namespace: temporal
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://go.temporal.io/helm-charts
    chart: temporal
    targetRevision: 0.58.0
    helm:
      valuesObject:
        additionalLabels:
          istio.io/dataplane-mode: ambient
        server:
          replicaCount: 1
          config:
            namespaces:
              create: true
              namespace:
                - name: default
                  retention: 3d
        cassandra:
          config:
            cluster_size: 1
        elasticsearch:
          replicas: 1
        prometheus:
          enabled: false
        grafana:
          enabled: false
        web:
          additionalEnv:
            - name: TEMPORAL_DISABLE_WRITE_ACTIONS
              value: "true"
            - name: TEMPORAL_AUTH_ENABLED
              value: "true"
            - name: TEMPORAL_AUTH_PROVIDER_URL
              value: "https://dex.cloudlab.khuedoan.com"
            - name: TEMPORAL_AUTH_ISSUER_URL
              value: "https://dex.cloudlab.khuedoan.com"
            - name: TEMPORAL_AUTH_CLIENT_ID
              value: "temporal"
            - name: TEMPORAL_AUTH_CALLBACK_URL
              value: "https://temporal.cloudlab.khuedoan.com/auth/sso/callback"
            - name: TEMPORAL_AUTH_SCOPES
              value: "openid,profile,email"
          additionalEnvSecretName: temporal-web
          ingress:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - temporal.cloudlab.khuedoan.com
            tls:
              - secretName: temporal-tls-certificate
                hosts:
                  - temporal.cloudlab.khuedoan.com
