defaultPodOptions:
  labels:
    "istio.io/dataplane-mode": "ambient"
controllers:
  main:
    containers:
      main:
        image:
          repository: docker.io/actualbudget/actual-server
          tag: 25.6.1-alpine
service:
  main:
    controller: main
    ports:
      http:
        port: 5006
        protocol: HTTP
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: budget.127.0.0.1.sslip.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - budget.127.0.0.1.sslip.io
        secretName: actualbudget-tls-certificate
persistence:
  data:
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /data
